name: Feature Request
description: Suggest an idea for this project
title: '[FEATURE] <title>'
labels: ["Category::Enhancement", "Type::Report"]
body:
- type: checkboxes
  attributes:
    label: 'Pre-checks'
    description: 'Check the boxes that apply'
    options:
      - label: 'I have searched the [issues](https://github.com/kqnade/CHaserLua/issues) of this repository and believe that this is not a duplicate.'
        required: true
      - label: 'I have searched the [documentation](https://github.com/kqnade/CHaserLua/readme.md) and believe that my request is not covered.'
        required: true
- type: textarea
  attributes:
    label: 'Describe the request'
    description: 'A clear and concise description of what the request is.'
    placeholder: 'I was trying to [...] but [...]'
    render: shell
- type: textarea
  attributes:
    label: 'Describe the solution you would like'
    description: 'A clear and concise description of what you want to happen.'
    placeholder: 'I would like [...] to happen because [...].'
    render: shell
- type: textarea
  attributes:
    label: 'Describe alternatives you have considered'
    description: 'A clear and concise description of any alternative solutions or features you have considered.'
    placeholder: 'I have also considered [...] but [...].'
    render: shell
- type: textarea
  attributes:
    label: 'Additional context'
    description: 'Add any other context or screenshots about the feature request here.'
    render: shell