name: Feature Request
description: Suggest an idea for this project
title: '[FEATURE] <title>'
labels: enhancement
body:
- type: checkboxes
  attributes:
    label: 'Checkboxes'
    description: 'Check the boxes that apply'
    options:
      - label: 'I have searched the [issues](https://github.com/kqnade/CHaserLua/issues) of this repository and believe that this is not a duplicate.'
        required: true
      - label: 'I have searched the [documentation](https://github.com/kqnade/CHaserLua/readme.md) and believe that my request is not covered.'
        required: true
- type: textarea
  attributes:
    label: 'Is your feature request related to a problem? Please describe.'
    description: 'A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]'
    placeholder: 'I was trying to [...] but [...]'
    render: shell
- type: textarea
  attributes:
    label: 'Describe the solution you'd like'
    description: 'A clear and concise description of what you want to happen.'
    placeholder: 'I expected [...] to happen because [...].'
    render: shell
- type: textarea
  attributes:
    label: 'Describe alternatives you've considered'
    description: 'A clear and concise description of any alternative solutions or features you've considered.'
    render: shell
- type: textarea
  attributes:
    label: 'Additional context'
    description: 'Add any other context or screenshots about the feature request here.'
    render: shell